name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["aranya-project/1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        If you need to report a security bug, please report it at securityreports@spideroak.com rather than creating an issue.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Aranya Software Version
      description: What version of Aranya were you running?
      placeholder: Aranya Software Version
      value: "Aranya Software Version"
    validations:
      required: true
  - type: textarea
    id: hardware
    attributes:
      label: Hardware?
      description: What hardware are you seeing this issue on?
      placeholder: Hardware Info
      value: "Hardware Info"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce?
      description: What are the steps to reproduce the issue?
      placeholder: How To Reproduce the issue
      value: "How To Reproduce the issue"
    validations:
      required: true
  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions?
      description: Do you have any suggestions for how to resolve this issue?
      placeholder: Suggestions
      value: "Suggestions"
    validations:
      required: false
  - type: input
    id: name
    attributes:
      label: Name?
      description: Your name if you'd like to be credited for reporting this bug
      placeholder: Your Name
      value: "Your Name"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/aranya-project/.github/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
