blank_issues_enabled: true
contact_links:
  - name: Aranya Community Support
    url: https://github.com/orgs/aranya-project/discussions
    about: Please ask and answer questions here.
  - name: Aranya Security Reporting
    url: securityreports@spideroak.com
    about: Please report security vulnerabilities here.
