name: Feature Request
description: Submit a feature request.
title: "[Feature]: "
labels: ["feature", "triage"]
projects: ["aranya-project/1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        If you need to report a security bug, please report it at securityreports@spideroak.com rather than creating an issue.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: Please describe the feature you would like to see implemented
      placeholder: Feature Description
      value: "Feature Description"
    validations:
      required: true
  - type: textarea
    id: importance
    attributes:
      label: Feature Importance
      description: Please describe why this feature is important
      placeholder: Feature Importance
      value: "Feature Importance"
    validations:
      required: true
  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions?
      description: Do you have any suggestions for how to implement this feature?
      placeholder: Suggestions
      value: "Suggestions"
    validations:
      required: false
  - type: input
    id: name
    attributes:
      label: Name?
      description: Your name if you'd like to be credited for requesting this feature
      placeholder: Your Name
      value: "Your Name"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/aranya-project/.github/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
